### ISSUE TITLE
Connection Failure: [error] <0.686.0> {bad_header,<<0,0,0,12,0,17,0,1>>}

### ISSUE THREAD

**Issue by Ahmard** [rabbitmq/rabbitmq-stream-rust-client#209]
### Describe the bug

Hello guy, I'm trying to connect to RMQ using this lib but the server keeps closing my connection with following error message
`[error] <0.686.0> {bad_header,<<0,0,0,12,0,17,0,1>>}`

Below is my client builder
```rust
Environment::builder()
        .host("localhost")
        .port(5672)
        .username("user")
        .password("password")
        .build()
        .await
```

I am using RMQ docker image `rabbitmq:3.12-management-alpine`
Below is my docker-compose.yml content
```yml
version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: my-rabbitmq
    hostname: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "5552:5552"
      - "15672:15672"
    volumes:
      - "./.volumes/rabbitmq/data/:/var/lib/rabbitmq/"
      - "./.volumes/rabbitmq/log/:/var/log/rabbitmq"
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "node_health_check" ]
      interval: 1m30s
      timeout: 5s
      retries: 3
      start_period: 30s
```

### Reproduction steps

1. Start RMQ using above docker image
2. Try to connect using above config
3.
...

### Expected behavior

To connect to the server
